apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cf-app
  template:
    metadata:
      labels:
        app: cf-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
